### ISSUE TITLE
posit<64,3> warnings on 32bit platform

### ISSUE THREAD

**Issue by thorsten-ottosen** [stillwater-sc/universal#220] opened 2021-03-25 09:33 UTC
Hello Devs.

First of all, thanks for taking on this very important piece of work.

I'm using your 3.0 project on 32bit windows. I get some warnings that I'm uncomfortable with, given the operations involved.

Here they are (for the type posit<64,3>):

posit.hpp(159): warning C4244: 'argument': conversion from 'int64_t' to 'size_t', possible loss of data
posit.hpp(176): warning C4244: 'argument': conversion from 'unsigned __int64' to 'size_t', possible loss of data

so on my platform size_t is 32 bit. I can understand that there might be a need to cast to size_t sometimes, but can't help thinking that e.g. defining any member variable (e.g. `es`) as size_t is unfortunate. Should std::uint32_t not be sufficient for `es`? 

The first warning is in this code:

```
_exp[size_t(es - 1ull - i)]
```
so the problem here is the suffix `ull`. Writing `ul` should fix it. Maybe the size_t cast is not really needed.

The second warning appears in this code:

```
_frac[fbits - 1ull - (msb - i)]
```
here changing `1ull` is not enough as `msb` is also 64bit.

**Comment by Ravenwater** [comment] 2021-03-25 10:57
@thorsten-ottosen thanks for reporting this.

In a nutshell, these explicit casts were introduced to make MSVC compiler happy. However, we do not test on 32-bit platforms, and that is an oversight we will fix. Let me take a look and I'll report back here.

**Comment by thorsten-ottosen** [comment] 2021-03-25 13:25
Thanks.

I have one additional question: (I apologize if this the wrong place to ask it) I was looking at the implementation, also the fast specializations; they don't work for my compiler (visual C++ 2017) right now, but that's probably fixable ...  my question is if you have considered using C++ bit fields to define sign, es, regime & fraction? I can't say if this improves the speed of posit<32,2>/posit<64,3>, but perhaps if makes the code easier to write/read.

**Comment by Ravenwater** [comment] 2021-03-28 19:14
@thorsten-ottosen : bit fields to manipulate a posit won't work as the bit fields in posits are variable. We do use them for native float code/decode, but since that is not C++ constexpr capable, we have just removed the bit fields with the proper C++20 <bits> library implementation. So now the newer floating-point types (bfloat and areal) support constexpr.

**Comment by Ravenwater** [comment] 2021-03-28 19:18
@thorsten-ottosen 

I double checked the Win32 regression results and they pass for the native 32bit platform:
```
Build started...
1>------ Build started: Project: RUN_TESTS, Configuration: Release Win32 ------
1>Test project C:/Users/tomtz/Documents/dev/win32/universal/build
1>        Start   1: posit_api
1>  1/162 Test   #1: posit_api ................................   Passed    0.06 sec
1>        Start   2: posit_assignment
1>  2/162 Test   #2: posit_assignment .........................   Passed    0.04 sec
1>        Start   3: posit_casting
1>  3/162 Test   #3: posit_casting ............................   Passed    0.03 sec
1>        Start   4: posit_constexpr_test
1>  4/162 Test   #4: posit_constexpr_test .....................   Passed    0.03 sec
1>        Start   5: posit_decode
1>  5/162 Test   #5: posit_decode .............................   Passed    0.04 sec
1>        Start   6: posit_numeric_limits
1>  6/162 Test   #6: posit_numeric_limits .....................   Passed    0.04 sec
1>        Start   7: posit_postfix
1>  7/162 Test   #7: posit_postfix ............................   Passed    0.03 sec
1>        Start   8: posit_prefix
1>  8/162 Test   #8: posit_prefix .............................   Passed    0.03 sec
1>        Start   9: posit_quire_accumulation
1>  9/162 Test   #9: posit_quire_accumulation .................   Passed    0.05 sec
1>        Start  10: posit_reciprocal_tables
1> 10/162 Test  #10: posit_reciprocal_tables ..................   Passed    0.03 sec
1>        Start  11: posit_serialization
1> 11/162 Test  #11: posit_serialization ......................   Passed    0.03 sec
1>        Start  12: posit_conversion
1> 12/162 Test  #12: posit_conversion .........................   Passed    1.37 sec
1>        Start  13: posit_conversion_functions
1> 13/162 Test  #13: posit_conversion_functions ...............   Passed    0.05 sec
1>        Start  14: posit_logic
1> 14/162 Test  #14: posit_logic ..............................   Passed    0.24 sec
1>        Start  15: posit_addition
1> 15/162 Test  #15: posit_addition ...........................   Passed    0.46 sec
1>        Start  16: posit_complex_add
1> 16/162 Test  #16: posit_complex_add ........................   Passed    3.76 sec
1>        Start  17: posit_decrement
1> 17/162 Test  #17: posit_decrement ..........................   Passed    0.05 sec
1>        Start  18: posit_division
1> 18/162 Test  #18: posit_division ...........................   Passed    0.59 sec
1>        Start  19: posit_fma
1> 19/162 Test  #19: posit_fma ................................   Passed    0.03 sec
1>        Start  20: posit_increment
1> 20/162 Test  #20: posit_increment ..........................   Passed    0.03 sec
1>        Start  21: posit_literals
1> 21/162 Test  #21: posit_literals ...........................   Passed    2.86 sec
1>        Start  22: posit_multiplication
1> 22/162 Test  #22: posit_multiplication .....................   Passed    0.43 sec
1>        Start  23: posit_negation
1> 23/162 Test  #23: posit_negation ...........................   Passed    0.09 sec
1>        Start  24: posit_reciprocation
1> 24/162 Test  #24: posit_reciprocation ......................   Passed   11.39 sec
1>        Start  25: posit_sqrt
1> 25/162 Test  #25: posit_sqrt ...............................   Passed    0.23 sec
1>        Start  26: posit_subtraction
1> 26/162 Test  #26: posit_subtraction ........................   Passed    0.41 sec
1>        Start  27: posit_classify
1> 27/162 Test  #27: posit_classify ...........................   Passed    0.03 sec
1>        Start  28: posit_exponent
1> 28/162 Test  #28: posit_exponent ...........................   Passed    0.35 sec
1>        Start  29: posit_hyperbolic
1> 29/162 Test  #29: posit_hyperbolic .........................   Passed    0.04 sec
1>        Start  30: posit_logarithm
1> 30/162 Test  #30: posit_logarithm ..........................   Passed    0.03 sec
1>        Start  31: posit_pow
1> 31/162 Test  #31: posit_pow ................................   Passed    0.27 sec
1>        Start  32: posit_trigonometry
1> 32/162 Test  #32: posit_trigonometry .......................   Passed    0.05 sec
1>        Start  33: posit_truncate
1> 33/162 Test  #33: posit_truncate ...........................   Passed    0.03 sec
1>        Start  34: fast_posit_128_4
1> 34/162 Test  #34: fast_posit_128_4 .........................   Passed    3.83 sec
1>        Start  35: fast_posit_16_1
1> 35/162 Test  #35: fast_posit_16_1 ..........................   Passed   24.68 sec
1>        Start  36: fast_posit_256_5
1> 36/162 Test  #36: fast_posit_256_5 .........................   Passed   12.78 sec
1>        Start  37: fast_posit_2_0
1> 37/162 Test  #37: fast_posit_2_0 ...........................   Passed    0.04 sec
1>        Start  38: fast_posit_32_2
1> 38/162 Test  #38: fast_posit_32_2 ..........................   Passed   39.01 sec
1>        Start  39: fast_posit_3_0
1> 39/162 Test  #39: fast_posit_3_0 ...........................   Passed    0.04 sec
1>        Start  40: fast_posit_48_2
1> 40/162 Test  #40: fast_posit_48_2 ..........................   Passed   14.62 sec
1>        Start  41: fast_posit_4_0
1> 41/162 Test  #41: fast_posit_4_0 ...........................   Passed    0.04 sec
1>        Start  42: fast_posit_64_3
1> 42/162 Test  #42: fast_posit_64_3 ..........................   Passed   22.25 sec
1>        Start  43: fast_posit_8_0
1> 43/162 Test  #43: fast_posit_8_0 ...........................   Passed    0.14 sec
1>        Start  44: fast_posit_8_1
1> 44/162 Test  #44: fast_posit_8_1 ...........................   Passed    0.36 sec
1>        Start  45: fast_quire_32_2
1> 45/162 Test  #45: fast_quire_32_2 ..........................   Passed    2.31 sec
1>        Start  46: aposit_add
1> 46/162 Test  #46: aposit_add ...............................   Passed    0.04 sec
1>        Start  47: areal
1> 47/162 Test  #47: areal ....................................   Passed    0.03 sec
1>        Start  48: double
1> 48/162 Test  #48: double ...................................   Passed    0.03 sec
1>        Start  49: fixpnt
1> 49/162 Test  #49: fixpnt ...................................   Passed    0.03 sec
1>        Start  50: float
1> 50/162 Test  #50: float ....................................   Passed    0.03 sec
1>        Start  51: float2posit
1> 51/162 Test  #51: float2posit ..............................   Passed    0.03 sec
1>        Start  52: ieee
1> 52/162 Test  #52: ieee .....................................   Passed    0.03 sec
1>        Start  53: lns
1> 53/162 Test  #53: lns ......................................   Passed    0.03 sec
1>        Start  54: longdouble
1> 54/162 Test  #54: longdouble ...............................   Passed    0.03 sec
1>        Start  55: plimits
1> 55/162 Test  #55: plimits ..................................   Passed    0.03 sec
1>        Start  56: posit
1> 56/162 Test  #56: posit ....................................   Passed    0.03 sec
1>        Start  57: propenv
1> 57/162 Test  #57: propenv ..................................   Passed    0.03 sec
1>        Start  58: propp
1> 58/162 Test  #58: propp ....................................   Passed    0.03 sec
1>        Start  59: propq
1> 59/162 Test  #59: propq ....................................   Passed    0.03 sec
1>        Start  60: signedint
1> 60/162 Test  #60: signedint ................................   Passed    0.03 sec
1>        Start  61: unsignedint
1> 61/162 Test  #61: unsignedint ..............................   Passed    0.03 sec
1>        Start  62: utils_lookup_arithmetic
1> 62/162 Test  #62: utils_lookup_arithmetic ..................   Passed    0.03 sec
1>        Start  63: utils_reverse_view
1> 63/162 Test  #63: utils_reverse_view .......................   Passed    0.03 sec
1>        Start  64: edu_tables_areals
1> 64/162 Test  #64: edu_tables_areals ........................   Passed    0.04 sec
1>        Start  65: edu_tables_bfloats
1> 65/162 Test  #65: edu_tables_bfloats .......................   Passed    0.06 sec
1>        Start  66: edu_tables_fixpnts
1> 66/162 Test  #66: edu_tables_fixpnts .......................   Passed    0.15 sec
1>        Start  67: edu_tables_posits
1> 67/162 Test  #67: edu_tables_posits ........................   Passed    0.06 sec
1>        Start  68: edu_integer_basic_operators
1> 68/162 Test  #68: edu_integer_basic_operators ..............   Passed    0.03 sec
1>        Start  69: edu_fixpnt_basic_operators
1> 69/162 Test  #69: edu_fixpnt_basic_operators ...............   Passed    0.03 sec
1>        Start  70: edu_bfloat_basic_operators
1> 70/162 Test  #70: edu_bfloat_basic_operators ...............   Passed    0.03 sec
1>        Start  71: edu_areal_basic_operators
1> 71/162 Test  #71: edu_areal_basic_operators ................   Passed    0.03 sec
1>        Start  72: edu_unum_basic_operators
1> 72/162 Test  #72: edu_unum_basic_operators .................   Passed    0.03 sec
1>        Start  73: edu_posit_basic_operators
1> 73/162 Test  #73: edu_posit_basic_operators ................   Passed    0.03 sec
1>        Start  74: edu_posit_components
1> 74/162 Test  #74: edu_posit_components .....................   Passed    0.03 sec
1>        Start  75: edu_posit_conversion
1> 75/162 Test  #75: edu_posit_conversion .....................   Passed    0.03 sec
1>        Start  76: edu_posit_discretization_curves
1> 76/162 Test  #76: edu_posit_discretization_curves ..........   Passed    0.03 sec
1>        Start  77: edu_posit_enumeration
1> 77/162 Test  #77: edu_posit_enumeration ....................   Passed    0.03 sec
1>        Start  78: edu_posit_exceptions
1> 78/162 Test  #78: edu_posit_exceptions .....................   Passed    0.03 sec
1>        Start  79: edu_posit_exponents
1> 79/162 Test  #79: edu_posit_exponents ......................   Passed    0.03 sec
1>        Start  80: edu_posit_extract
1> 80/162 Test  #80: edu_posit_extract ........................   Passed    0.03 sec
1>        Start  81: edu_posit_fractions
1> 81/162 Test  #81: edu_posit_fractions ......................   Passed    0.07 sec
1>        Start  82: edu_posit_raw_bit_patterns
1> 82/162 Test  #82: edu_posit_raw_bit_patterns ...............   Passed    0.03 sec
1>        Start  83: edu_posit_regimes
1> 83/162 Test  #83: edu_posit_regimes ........................   Passed    0.03 sec
1>        Start  84: edu_posit_scales
1> 84/162 Test  #84: edu_posit_scales .........................   Passed    0.04 sec
1>        Start  85: edu_posit_serialization
1> 85/162 Test  #85: edu_posit_serialization ..................   Passed    0.03 sec
1>        Start  86: edu_posit_signalling_nar
1> 86/162 Test  #86: edu_posit_signalling_nar .................   Passed    0.03 sec
1>        Start  87: edu_posit_ulp
1> 87/162 Test  #87: edu_posit_ulp ............................   Passed    0.54 sec
1>        Start  88: edu_posit_values
1> 88/162 Test  #88: edu_posit_values .........................   Passed    0.03 sec
1>        Start  89: edu_quire_quires
1> 89/162 Test  #89: edu_quire_quires .........................   Passed    0.03 sec
1>        Start  90: edu_valid_intervals
1> 90/162 Test  #90: edu_valid_intervals ......................   Passed    0.03 sec
1>        Start  91: edu_lns_basic_operators
1> 91/162 Test  #91: edu_lns_basic_operators ..................   Passed    0.03 sec
1>        Start  92: blas_hilbert
1> 92/162 Test  #92: blas_hilbert .............................   Passed    0.33 sec
1>        Start  93: blas_inverse
1> 93/162 Test  #93: blas_inverse .............................   Passed    0.06 sec
1>        Start  94: blas_l1_fused_dot
1> 94/162 Test  #94: blas_l1_fused_dot ........................   Passed    0.03 sec
1>        Start  95: blas_l2_fused_mv
1> 95/162 Test  #95: blas_l2_fused_mv .........................   Passed    0.03 sec
1>        Start  96: blas_l3_fused_mm
1> 96/162 Test  #96: blas_l3_fused_mm .........................   Passed    0.04 sec
1>        Start  97: blas_lu
1> 97/162 Test  #97: blas_lu ..................................   Passed    0.04 sec
1>        Start  98: blas_norms
1> 98/162 Test  #98: blas_norms ...............................   Passed    0.03 sec
1>        Start  99: chaos_bakers_map
1> 99/162 Test  #99: chaos_bakers_map .........................   Passed    0.04 sec
1>        Start 100: chaos_time_precision_lyapunov
1>100/162 Test #100: chaos_time_precision_lyapunov ............   Passed    0.03 sec
1>        Start 101: cheby_nodes
1>101/162 Test #101: cheby_nodes ..............................   Passed    0.03 sec
1>        Start 102: cheby_skeleton
1>102/162 Test #102: cheby_skeleton ...........................   Passed    0.03 sec
1>        Start 103: complex_compute
1>103/162 Test #103: complex_compute ..........................   Passed    0.03 sec
1>        Start 104: crypto_fermat
1>104/162 Test #104: crypto_fermat ............................   Passed    3.03 sec
1>        Start 105: crypto_large_lcm
1>105/162 Test #105: crypto_large_lcm .........................   Passed   20.24 sec
1>        Start 106: crypto_pollard_rho
1>106/162 Test #106: crypto_pollard_rho .......................   Passed    0.04 sec
1>        Start 107: crypto_quadratic_sieve
1>107/162 Test #107: crypto_quadratic_sieve ...................   Passed    0.03 sec
1>        Start 108: dsp_adc_mapping
1>108/162 Test #108: dsp_adc_mapping ..........................   Passed    0.04 sec
1>        Start 109: dsp_fir_filter
1>109/162 Test #109: dsp_fir_filter ...........................   Passed    0.04 sec
1>        Start 110: engineering_chem_equilibrium
1>110/162 Test #110: engineering_chem_equilibrium .............   Passed    0.03 sec
1>        Start 111: engineering_water
1>111/162 Test #111: engineering_water ........................   Passed    0.03 sec
1>        Start 112: math_decimal_lpp
1>112/162 Test #112: math_decimal_lpp .........................   Passed    8.34 sec
1>        Start 113: math_distinct_powers
1>113/162 Test #113: math_distinct_powers .....................   Passed    0.03 sec
1>        Start 114: math_largest_palindrome_product
1>114/162 Test #114: math_largest_palindrome_product ..........   Passed    0.30 sec
1>        Start 115: math_numbers_irrational
1>115/162 Test #115: math_numbers_irrational ..................   Passed    0.07 sec
1>        Start 116: math_numbers_rational
1>116/162 Test #116: math_numbers_rational ....................   Passed    0.03 sec
1>        Start 117: math_pascals_triangle
1>117/162 Test #117: math_pascals_triangle ....................   Passed    0.35 sec
1>        Start 118: math_primes
1>118/162 Test #118: math_primes ..............................   Passed   11.72 sec
1>        Start 119: math_sincospi
1>119/162 Test #119: math_sincospi ............................   Passed    0.03 sec
1>        Start 120: math_stirlings_approximation
1>120/162 Test #120: math_stirlings_approximation .............   Passed    0.10 sec
1>        Start 121: numeric_limits
1>121/162 Test #121: numeric_limits ...........................   Passed    0.03 sec
1>        Start 122: numeric_midpoint
1>122/162 Test #122: numeric_midpoint .........................   Passed    0.03 sec
1>        Start 123: numeric_numbers
1>123/162 Test #123: numeric_numbers ..........................   Passed    0.03 sec
1>        Start 124: numeric_posit_properties
1>124/162 Test #124: numeric_posit_properties .................   Passed    0.04 sec
1>        Start 125: numeric_residual
1>125/162 Test #125: numeric_residual .........................   Passed    0.06 sec
1>        Start 126: numeric_rump_equation
1>126/162 Test #126: numeric_rump_equation ....................   Passed    0.04 sec
1>        Start 127: numeric_ulp_math
1>127/162 Test #127: numeric_ulp_math .........................   Passed    0.03 sec
1>        Start 128: ode_first-order-ode
1>128/162 Test #128: ode_first-order-ode ......................   Passed    0.04 sec
1>        Start 129: ode_general-runge-kutta
1>129/162 Test #129: ode_general-runge-kutta ..................   Passed    0.03 sec
1>        Start 130: ode_rungekutta
1>130/162 Test #130: ode_rungekutta ...........................   Passed    0.05 sec
1>        Start 131: pde_cg
1>131/162 Test #131: pde_cg ...................................   Passed    5.02 sec
1>        Start 132: pde_gauss_seidel
1>132/162 Test #132: pde_gauss_seidel .........................   Passed    0.05 sec
1>        Start 133: pde_jacobi
1>133/162 Test #133: pde_jacobi ...............................   Passed    0.03 sec
1>        Start 134: pde_laplace
1>134/162 Test #134: pde_laplace ..............................   Passed    0.03 sec
1>        Start 135: pde_sor
1>135/162 Test #135: pde_sor ..................................   Passed    0.05 sec
1>        Start 136: roots_bisection
1>136/162 Test #136: roots_bisection ..........................   Passed    0.04 sec
1>        Start 137: roots_rpoly_ak1
1>137/162 Test #137: roots_rpoly_ak1 ..........................   Passed    0.03 sec
1>        Start 138: science_iso_constants
1>138/162 Test #138: science_iso_constants ....................   Passed    0.03 sec
1>        Start 139: science_physics_constants
1>139/162 Test #139: science_physics_constants ................   Passed    0.04 sec
1>        Start 140: sequences_fibonacci
1>140/162 Test #140: sequences_fibonacci ......................   Passed    0.05 sec
1>        Start 141: sequences_tribonacci
1>141/162 Test #141: sequences_tribonacci .....................   Passed    0.05 sec
1>        Start 142: stl_sequential_containers
1>142/162 Test #142: stl_sequential_containers ................   Passed   27.00 sec
1>        Start 143: trig_arbitrary_precision_pi
1>143/162 Test #143: trig_arbitrary_precision_pi ..............   Passed    0.33 sec
1>        Start 144: weather_error_growth_atmospheric_model
1>144/162 Test #144: weather_error_growth_atmospheric_model ...   Passed    0.03 sec
1>        Start 145: mp_secant
1>145/162 Test #145: mp_secant ................................   Passed    0.03 sec
1>        Start 146: mp_taylor
1>146/162 Test #146: mp_taylor ................................   Passed    0.03 sec
1>        Start 147: mp_simpson
1>147/162 Test #147: mp_simpson ...............................   Passed    0.04 sec
1>        Start 148: mp_trapezoidal
1>148/162 Test #148: mp_trapezoidal ...........................   Passed    0.03 sec
1>        Start 149: mp_spline
1>149/162 Test #149: mp_spline ................................   Passed    0.03 sec
1>        Start 150: optimal_secant
1>150/162 Test #150: optimal_secant ...........................   Passed    0.02 sec
1>        Start 151: mp_cg
1>151/162 Test #151: mp_cg ....................................   Passed    0.04 sec
1>        Start 152: mp_cg_mvdot_cmpdot
1>152/162 Test #152: mp_cg_mvdot_cmpdot .......................   Passed    3.71 sec
1>        Start 153: mp_cg_mvdot_cmpfdp
1>153/162 Test #153: mp_cg_mvdot_cmpfdp .......................   Passed    3.78 sec
1>        Start 154: mp_cg_mvfdp_cmpdot
1>154/162 Test #154: mp_cg_mvfdp_cmpdot .......................   Passed    4.67 sec
1>        Start 155: mp_cg_mvfdp_cmpfdp
1>155/162 Test #155: mp_cg_mvfdp_cmpfdp .......................   Passed    3.71 sec
1>        Start 156: playground_efunc_posits
1>156/162 Test #156: playground_efunc_posits ..................   Passed    0.04 sec
1>        Start 157: playground_efunc_valids
1>157/162 Test #157: playground_efunc_valids ..................   Passed    0.03 sec
1>        Start 158: playground_gismo_test
1>158/162 Test #158: playground_gismo_test ....................   Passed    0.04 sec
1>        Start 159: playground_meta_programming
1>159/162 Test #159: playground_meta_programming ..............   Passed    0.04 sec
1>        Start 160: playground_serialization
1>160/162 Test #160: playground_serialization .................   Passed    0.04 sec
1>        Start 161: playground_skeleton
1>161/162 Test #161: playground_skeleton ......................   Passed    0.06 sec
1>        Start 162: playground_type_test
1>162/162 Test #162: playground_type_test .....................   Passed    0.03 sec
1>
1>100% tests passed, 0 tests failed out of 162
```

The reason this is the case is that the 64bit-ness of the expression addresses a bit by value. That implies that for a 64-bit posit with a max of 61 fraction bits (posit<64,0>) the expression would only use the bottom 6 bits. Otherwise stated, any truncation of a 64bit index value to 32bits will always yield a correct index for a 64-bit posit.

I do need to find a way to clean up that code so that these warnings are removed, so I won't close this issue until I got that done.

**Comment by thorsten-ottosen** [comment] 2021-04-08 07:56
Thanks for the explanation.

**Comment by thorsten-ottosen** [comment] 2021-04-09 08:46
I'm now getting a direct crash with visual C++ from the code in line 159:

```
	_exp[size_t(es - 1ull - i)] = tmp[msb - i];
```

The problem is with `msb`:

```
	// start of exponent is nbits-1 - (sign_bit + regime_bits)
	int64_t msb = static_cast<int64_t>(nbits - 1ul - (1ul + nrRegimeBits));
```

`nbits` is 64 and `nrRegimeBits` 63. So the sum (63 - 1) - 64 wraps around since its unsigned, well-defined, but leads to a very large msb, which then leads to failure in line 159. I think it could be useful to employ some assertions on the range of things to catch breaking expectations early on (for example assert( msb >= 0 && msb <= nbits ) ).

Minimal test case to reproduce:

```
        using T = sw::universal::posit<64,3>;
        auto val = T(9.01);
        auto product = val * std::numeric_limits<T>::min();
```

**Comment by thorsten-ottosen** [comment] 2021-04-09 10:25
Let me expand a little on how one could add a small helper class that could make the code more explicit in its assumptions (untested code)

```
template< class T, T min, T max >
struct constrained_value
{
   T value;


    template< class U >
    constrained_value( U u ) noexcept :  value( static_cast<T>( u ) )
    {
         assert( static_cast<U>( value ) == u );
         assert( value >= min );
         assert( value <= max );
    }

    constrained_value( T t ) noexcept : value( t ) 
    {
         assert( value >= min );
         assert( value <= max );
    }
    operator T() const noexcept
    { 
         return value;
    }
};

using msb_type = constained_value<int64_t,0,X>;
```

**Comment by Ravenwater** [comment] 2021-04-09 10:40
@thorsten-ottosen thanks for that RCA. Can you share the driver/application that triggered it, I would like to add those to the regression suite. Looks like a minpos/maxpos case, but I like to know more.

**Comment by thorsten-ottosen** [comment] 2021-04-09 11:19
I can share the code, but the example above is all that should be needed to trigger the problem. But it depends on boost (boost.test and other libs). 

My compiler is the following:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27044 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```

running on windows. In release mode it just crashed, in debug mode an assertion fire in bitset. Do you need more?

**Comment by Ravenwater** [comment] 2021-04-09 11:46
Not able to reproduce your error:

![image](https://user-images.githubusercontent.com/466641/114174303-706d5900-9906-11eb-9932-4ed19cb309d9.png)

![image](https://user-images.githubusercontent.com/466641/114174193-47e55f00-9906-11eb-9291-694b6747c626.png)

I need more context to reproduce your error.

**Comment by thorsten-ottosen** [comment] 2021-04-09 12:03
Ok. It's a 32-bit binary, built on 64 bit windows 10 OS. It is version 3.0.0 of the universal lib. Compile flags include:

```
-std:c++17  /GR /EHsc  /GS- /Zc:rvalueCast,referenceBinding 
```

**Comment by Ravenwater** [comment] 2021-04-09 13:14
I am postulating that you found some dead code in the library. I am cleaning that up and will merge that into master.

**Closed by Ravenwater** 2021-04-09 13:14 UTC

**Comment by Ravenwater** [comment] 2021-04-09 14:02
I am now guarding the fast specialization requests, if we don't have a fast specialization implementation available yet:
```
5>Fast specialization of posit<2,0>
4>Fast specialization of posit<256,4> requested but ignored as fast implemention is TBD
2>Fast specialization of posit<128,4> requested but ignored as fast implemention is TBD
6>Fast specialization of posit<32,2>
7>Fast specialization of posit<3,0>
11>Fast specialization of posit<8,0>
13>Fast specialization of posit<32,2>
9>Fast specialization of posit<4,0>
10>Fast specialization of posit<64,3> requested but ignored as fast implemention is TBD
8>Fast specialization of posit<48,2> requested but ignored as fast implemention is TBD
```

You found the dead code that I had guarded in the header <universal/posit/posit>. I am now guarding it in the actual specialization file, providing better compilation feedback.

Thank you for taking the time to RCA it, so that we can make the library better.

**Comment by Ravenwater** [comment] 2021-04-09 15:15
[commit](https://github.com/stillwater-sc/universal/commit/2965d92589e6479e73ecf57c2558c6a980d38730) fixes this issue

**Comment by thorsten-ottosen** [comment] 2021-04-13 12:57
I tried again after a complete cleanup of my cmake build-folders, and now the code works without problems.

Apologies for the noise. Thanks for the feedback.

**Comment by Ravenwater** [comment] 2021-04-13 22:29
You did find a problem, so you raised just the right level of noise. 

I am glad this resolved the issue. Let me know if you use posit<64,3> (or the new standard posit<64,2>) a lot. We can work on making it faster.

**Comment by thorsten-ottosen** [comment] 2021-04-14 11:33
My plan was to use posit<64,4> (based on the range given in  Gustafson & Yonemoto), but I can see that I actually used posit<63,3> since that is what you used in your paper. Is there any particluar reason you choose to specialize posit<32,2> and posit<64,3> instead of posit<32,3> and posit<64,4> ?

**Comment by Ravenwater** [comment] 2021-04-14 12:28
The posit reference standard started off with this set of byte-aligned posits:
```
posit<8,0>
posit<16,1>
posit<32,2>
posit<64,3>
posit<128,4>
posit<256,5>
```
That is what you will see being used throughout the Universal library educational and application examples.

However, application usage revealed that the posit<8,0> doesn't have quite the dynamic range needed to be widely useful. In particular, for DL, the posit<8,2> was found to be a good fit, enabling training at accuracy competitive with fp32. This has lead to the latest posit standard to propose the following 'standard' byte-aligned posits:
```
posit<8,2>
posit<16,2>
posit<32,2>
posit<64,2>
```
This design also supports up and down conversions at lower cost.

As I indicated, the Universal roadmap includes a new block-based computational class (the blocktriple) to make all the `Real` number systems faster. This is being development with the bfloat and areal and when we feel we have the basics in place, we will upgrade the posit class to use the blocktriple, instead of the bitset.

**Comment by thorsten-ottosen** [comment] 2021-04-14 13:21
Ok.

In terms of performance, I think 100M pops is absolutely necessary for it to be used in production. In the short term, I can easily test with slower versions. I think I prefer posit<64,3>, but can test if it makes any practical difference to posit<64,2>. We work with Bayesian AI, so precision in [0,1] is important, but we need some precision around larger number too (using a quire seems prohibitive).

**Comment by Ravenwater** [comment] 2021-04-14 14:02
@thorsten-ottosen ok, let's make it a task to get you a fast posit<64,#>

**Comment by thorsten-ottosen** [comment] 2021-04-15 12:00
Thanks!
